{
  pkgs,
  pkgsUnstable ? pkgs,
  ...
}:

let
  tsWithGrammars = pkgsUnstable.vimPlugins.nvim-treesitter.withAllGrammars;

  treesitterParsers = pkgs.symlinkJoin {
    name = "treesitter-parsers";
    paths = tsWithGrammars.dependencies;
  };

  plugins = with pkgsUnstable.vimPlugins; [
    cmp-buffer
    cmp_luasnip
    cmp-nvim-lsp
    cmp-path
    gruvbox-nvim
    lazy-nvim
    lspkind-nvim
    mini-nvim
    nvim-cmp
    nvim-lspconfig
    nvim-lsp-file-operations
    nvim-tree-lua
    nvim-ts-autotag
    nvim-web-devicons
    plenary-nvim
    telescope-fzf-native-nvim
    telescope-nvim
    tsWithGrammars
    vim-fugitive
    which-key-nvim
  ];

  pluginPath = pkgs.linkFarm "lazy-plugins" (
    (map (p: {
      name = p.pname or p.name;
      path = p;
    }) plugins)
    ++ [
      # Manual override needed because lazy.nvim is looking for a directory
      # called "LuaSnip", but the Nix package is "luasnip".
      { name = "LuaSnip"; path = pkgsUnstable.vimPlugins.luasnip; }
    ]
  );
in
{
  programs.neovim.enable = true;
  #enable = true;
  #    package = pkgsUnstable.neovim-unwrapped;
  #};

  programs.fzf.enable = true;

  home.packages = with pkgsUnstable; [
    tree-sitter
  ];

  #home.file.".local/share/nvim/site/parser".source =
  #"${treesitterParsers}/parser";

  # Symlink in real Lua config
  xdg.configFile."nvim" = {
    source = ../../../../config/nvim;
    recursive = true;
  };

  xdg.configFile."nvim/lua/nix-plugins.lua".text = ''
    -- Auto-generated by Nix. Overwritten on each home-manager run.
    return {
      enabled = true,
      path = "${pluginPath}",
      parsers = "${treesitterParsers}",
    }
  '';
}
