{
  pkgs,
  pkgsUnstable ? pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.features.neovim;

  tsWithGrammars = pkgsUnstable.vimPlugins.nvim-treesitter.withAllGrammars;

  treesitterParsers = pkgs.symlinkJoin {
    name = "treesitter-parsers";
    paths = tsWithGrammars.dependencies;
  };

  basePlugins = with pkgsUnstable.vimPlugins; [
    cmp-buffer
    cmp_luasnip
    cmp-nvim-lsp
    cmp-path
    gruvbox-nvim
    lazy-nvim
    lspkind-nvim
    mini-nvim
    nvim-cmp
    nvim-lspconfig
    nvim-lsp-file-operations
    nvim-tree-lua
    nvim-ts-autotag
    nvim-web-devicons
    plenary-nvim
    telescope-fzf-native-nvim
    telescope-nvim
    tsWithGrammars
    vim-fugitive
    which-key-nvim
  ];

in
{
  options.features.neovim = {
    enable = lib.mkEnableOption "neovim";

    claude.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable Claude AI support plugins";
    };
  };

  config = lib.mkIf cfg.enable (
    let
      claudePlugins =
        with pkgsUnstable.vimPlugins;
        lib.optionals cfg.claude.enable [
          claudecode-nvim
        ];

      plugins = basePlugins ++ claudePlugins;

      pluginPath = pkgs.linkFarm "lazy-plugins" (
        (map (p: {
          name = p.pname or p.name;
          path = p;
        }) plugins)
        ++ [
          # Manual override needed because lazy.nvim is looking for a directory
          # called "LuaSnip", but the Nix package is "luasnip".
          {
            name = "LuaSnip";
            path = pkgsUnstable.vimPlugins.luasnip;
          }
        ]
      );
    in
    {
      programs.neovim = {
        enable = true;
        withRuby = false;
        withPython3 = false;
      };

      programs.fzf.enable = true;

      home.packages = with pkgsUnstable; [
        tree-sitter-mike
        typescript-language-server
      ];

      #home.file.".local/share/nvim/site/parser".source =
      #"${treesitterParsers}/parser";

      # Symlink in real Lua config
      xdg.configFile = {
        "nvim" = {
          source = ../../../../config/nvim;
          recursive = true;
        };
        "nvim/lua/nix-plugins.lua".text = ''
          -- Auto-generated by Nix. Overwritten on each home-manager run.
          return {
            enabled = true,
            path = "${pluginPath}",
            parsers = "${treesitterParsers}",
          }
        '';
      }
      // lib.optionalAttrs cfg.claude.enable {
        "nvim/lua/nix/claude.lua".source = ./nvim/lua/claude.lua;
      };

    }
  );
}
